// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kaufmann_Final.Models
{
    public partial class Driver
    {
        public Driver()
        {
            VehicleOwners = new HashSet<VehicleOwner>();
        }

        public string DriverLicenseNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SocialSecurity { get; set; }
        public DateTime DateOfBirth { get; set; }

        public virtual ICollection<VehicleOwner> VehicleOwners { get; set; }
    }
}