// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kaufmann_Final.Models
{
    public partial class VehicleOwner
    {
        public VehicleOwner()
        {
            Infractions = new HashSet<Infraction>();
        }

        public int VehicleOwnerId { get; set; }
        public string LicensePlate { get; set; }
        public string DriverLicenseNumber { get; set; }
        public DateTime TitleDateIssued { get; set; }

        public virtual Driver DriverLicenseNumberNavigation { get; set; }
        public virtual Vehicle LicensePlateNavigation { get; set; }
        public virtual ICollection<Infraction> Infractions { get; set; }
    }
}